from tkinter import * #Starting Tkinter
from PIL import Image, ImageTk #Starting Pillow for Images
main= Tk() #Creating the Window and setting its size
main.geometry('655x450')
main.title('Order Up')
def raise_frame(frame):#Creating a comand for swapping between the frames
    frame.tkraise()
    
def smallPizza():#Commands that set the text for each size of pizza
    pSize_lbl.config(text = "You ordered a Small Pizza: 5$")
def mediumPizza():
    pSize_lbl.config(text = "You ordered a Medium Pizza: 7.50$")
def largePizza():
    pSize_lbl.config(text = "You ordered a Large Pizza: 9$")

def Checkout():#This is the command for checking out after the order is complete
    resultT = ''#Variable that is used to hold toppings selected
    check=''#This gets the text generated by the size button, it starts blank so it can be used to see if a size has been pressed.
    numT=0#Number of Toppings
    total=0#total cost of order
    tax=0#Variable for the dollar amount of tax
    check=pSize_lbl.cget('text')#Getting the text
    name=name_entry.get()#Getting the Name entered
    address=address_entry.get()#Getting Address entered
    if len(name) > 0  and len(check) > 0  and len(address) > 0:#Makeing sure the entry fields are filled and a size of pizza selected
        for item in toppings_list.curselection():#Collecting toppings selected and creating a variable and string of the number selected
            resultT= resultT + str(toppings_list.get(item)) + "\n"
            numT+=0.50
            C_of_T=str("{:.2f}".format(numT))

        
        if check =="You ordered a Small Pizza: 5$":#Checking for Size selected
            tax = ((numT + 5)*.07)
            total=(numT + 5 + tax)
            totalStr=str("${:.2f}".format(total))
        
            total_lbl.config(text= 'Tax is 7 percent' + '\n' + 'The total cost of your pizza is:  ' + totalStr + '$')#Adding text to the receipt
        
        if check =="You ordered a Medium Pizza: 7.50$":
            tax = ((numT + 7.5)*.07)
            total=(numT + 7.5 + tax)
            totalStr=str("${:.2f}".format(total))
        
            total_lbl.config(text= 'Tax is 7 percent' + '\n' + 'The total cost of your pizza is:  ' + totalStr + '$')
        
        if check =="You ordered a Large Pizza: 9$":
            tax = ((numT + 9)*.07)
            total=(numT + 9 + tax)
            totalStr=str("${:.2f}".format(total))
        
            total_lbl.config(text= 'Tax is 7 percent' + '\n' + 'The total cost of your pizza is:  ' + totalStr + '$')
            
        RName_lbl.config(text= 'Name on order: ' + name)#filling receipt information
        RAddress_lbl.config(text= "Address for delivery: " + address)
        tList_lbl.config(text= "Your Pizza toppings: " + "\n" + resultT + '\n')
        tCost_lbl.config(text= "The cost of Toppings is: " + C_of_T + '$')
        raise_frame(secondPage)#pushing second frame to the front
    
def closemain():#exit command
    main.destroy()

mainPage = Frame(main)#Creating frames
secondPage = Frame(main)

for frame in (mainPage, secondPage):
    frame.grid(row=0,column=0, sticky='news')
    
name_label = Label(mainPage,text='Name for the order:')#Label for entry of name
name_label.grid(row=0, column=0)

name_entry = Entry(mainPage, width=20)#Entry to get name
name_entry.grid(row=0, column=1)

address_label = Label(mainPage,text='Address for delivery:')#Label for entry of address
address_label.grid(row=1, column=0)

address_entry = Entry(mainPage, width=20)#Entry for address
address_entry.grid(row=1, column=1)

#Sizes of Pizza
size_label = Label(mainPage,text='Pick a size of Pizza \nSmall = 5$ Medium = 7.50$ Large = 9$')
size_label.grid(row=2, column=1)

small_button = Button(mainPage, text='Small', command=smallPizza)
small_button.grid(row=3, column=0)

medium_button = Button(mainPage, text='Medium', command=mediumPizza)
medium_button.grid(row=3, column=1)

large_button = Button(mainPage, text='Large', command=largePizza)
large_button.grid(row=3, column=2)

toppings_label = Label(mainPage,text='Pick your toppings \nEach topping costs .50$')#Toppings
toppings_label.grid(row=4, column=1)

toppings = ('Pepperoni','Sausage','Ham ','Mushroom','Olives','Green Peppers','Onions','Extra Cheese')#Making List of Toppings

toppings_list = Listbox(mainPage, selectmode=MULTIPLE)#Creating a list box that allows multiple selection
toppings_list.grid(row=5, column=1)

for item in toppings:
    toppings_list.insert(0, item)

checkout_button= Button(mainPage, text= 'Checkout', command=Checkout)#Checkout Button
checkout_button.grid(row=6, column=1)

exit_button= Button(mainPage, text= 'Exit', command=closemain)#Exit button on first frame
exit_button.grid(row=7, column=1)

pizza_pic = ImageTk.PhotoImage(Image.open("pizza.jpg"))#Pizza images
pizza_pic_lbl = Label(mainPage, image=pizza_pic)
pizza_pic_lbl.grid(row=5,column=0)

pizza2_pic_lbl = Label(mainPage, image=pizza_pic)
pizza2_pic_lbl.grid(row=5,column=2)

RName_lbl=Label(secondPage, text='')#Name on receipt 
RName_lbl.grid(row=1,column=1)

RAddress_lbl=Label(secondPage, text='')#Address on receipt
RAddress_lbl.grid(row=2,column=1)

pSize_lbl=Label(secondPage, text='')#Size of Pizza ordered on receipt
pSize_lbl.grid(row=3,column=1)

tList_lbl = Label(secondPage, text='')#Lists out toppings ordered
tList_lbl.grid(row=4,column=1)

tCost_lbl = Label(secondPage, text='')#Toppings Cost display
tCost_lbl.grid(row=5,column=1)

total_lbl = Label(secondPage, text='')#Total price of Order
total_lbl.grid(row=6,column=1)

exit_button2= Button(secondPage, text= 'Exit', command=closemain)#Exit button on receipt
exit_button2.grid(row=8, column=1)

return_button= Button(secondPage, text= 'Order Another Pizza', command=lambda:raise_frame(mainPage))#Takes user back to order page
return_button.grid(row=7, column=1)

raise_frame(mainPage)
main.mainloop()
